### ISSUE TITLE
Need to double click folder after update

### ISSUE THREAD

**Issue by adifaidz** [h2so5/atom-chary-tree-view#5]
After the latest update to 0.2.5 and 0.2.7,  I found that I need to double-click folders to open them now. Is this intended? How can I turn it off?

**Comment by funkflute** [comment]
+1 would like an option to single-click folders.

**Comment by adifaidz** [comment]
Thanks, its working now 👍 👍

**Comment by Silviu-Marian** [comment]
well the problem is that it still opens the file on single click if you don't click the text (like click near the file on the same row)

**Comment by adifaidz** [comment]
@Silviu-Marian yeah just found that out the hard way haha

**Comment by adifaidz** [comment]
I think its because of this ? #1

**Comment by Silviu-Marian** [comment]
No, not really. I just checked the code. 

isOneOfThoseElements is essentially a file entry - you can rename it as such and it'll make more sense

Then you have to mix out the condition from line 24 to somewhere inside `entryClicked` - this way it'll capture clicks anywhere on the file row - and handle them against the new user setting

Let me know if you need any help :)
