### ISSUE TITLE
Atom 1.17.0 bug

### ISSUE THREAD

**Issue by Snoff** [h2so5/atom-chary-tree-view#7]
Plugin seem to be non functional with atom 1.17.0

**Comment by Silviu-Marian** [comment]
Change line 9 from 

`treeView = treeViewPkg.mainModule.createView();`
to
`treeView = treeViewPkg.mainModule.treeView;`

Everything should be back to normal.

**Comment by Snoff** [comment]
ok but how can i reinstall it ?
It's not possible to make a fix into the project ?

**Comment by Snoff** [comment]
Will you deploy a patch soon ?
